insert into provincias (codpro, nombre) values ('01','ALAVA');
insert into provincias (codpro, nombre) values ('02','ALBACETE');
insert into provincias (codpro, nombre) values ('03','ALICANTE');
insert into provincias (codpro, nombre) values ('04','ALMERIA');
insert into provincias (codpro, nombre) values ('05','AVILA');
insert into provincias (codpro, nombre) values ('06','BADAJOZ');
insert into provincias (codpro, nombre) values ('07','BALEARES');
insert into provincias (codpro, nombre) values ('08','BARCELONA');
insert into provincias (codpro, nombre) values ('09','BURGOS');
insert into provincias (codpro, nombre) values ('10','CACERES');
insert into provincias (codpro, nombre) values ('11','CADIZ');
insert into provincias (codpro, nombre) values ('12','CASTELLON');
insert into provincias (codpro, nombre) values ('13','CIUDAD REAL');
insert into provincias (codpro, nombre) values ('14','CORDOBA');
insert into provincias (codpro, nombre) values ('15','LA CORUQA');
insert into provincias (codpro, nombre) values ('16','CUENCA');
insert into provincias (codpro, nombre) values ('17','GERONA');
insert into provincias (codpro, nombre) values ('18','GRANADA');
insert into provincias (codpro, nombre) values ('19','GUADALAJARA');
insert into provincias (codpro, nombre) values ('20','GUIPUZCOA');
insert into provincias (codpro, nombre) values ('21','HUELVA');
insert into provincias (codpro, nombre) values ('22','HUESCA');
insert into provincias (codpro, nombre) values ('23','JAEN');
insert into provincias (codpro, nombre) values ('24','LEON');
insert into provincias (codpro, nombre) values ('25','LERIDA');
insert into provincias (codpro, nombre) values ('26','LA RIOJA');
insert into provincias (codpro, nombre) values ('27','LUGO');
insert into provincias (codpro, nombre) values ('28','MADRID');
insert into provincias (codpro, nombre) values ('29','MALAGA');
insert into provincias (codpro, nombre) values ('30','MURCIA');
insert into provincias (codpro, nombre) values ('31','NAVARRA');
insert into provincias (codpro, nombre) values ('32','ORENSE');
insert into provincias (codpro, nombre) values ('33','ASTURIAS');
insert into provincias (codpro, nombre) values ('34','PALENCIA');
insert into provincias (codpro, nombre) values ('35','LAS PALMAS');
insert into provincias (codpro, nombre) values ('36','PONTEVEDRA');
insert into provincias (codpro, nombre) values ('37','SALAMANCA');
insert into provincias (codpro, nombre) values ('38','STA CRUZ DE TENERIFE');
insert into provincias (codpro, nombre) values ('39','CANTABRIA');
insert into provincias (codpro, nombre) values ('40','SEGOVIA');
insert into provincias (codpro, nombre) values ('41','SEVILLA');
insert into provincias (codpro, nombre) values ('42','SORIA');
insert into provincias (codpro, nombre) values ('43','TARRAGONA');
insert into provincias (codpro, nombre) values ('44','TERUEL');
insert into provincias (codpro, nombre) values ('45','TOLEDO');
insert into provincias (codpro, nombre) values ('46','VALENCIA');
insert into provincias (codpro, nombre) values ('47','VALLADOLID');
insert into provincias (codpro, nombre) values ('48','VIZCAYA');
insert into provincias (codpro, nombre) values ('49','ZAMORA');
insert into provincias (codpro, nombre) values ('50','ZARAGOZA');
insert into provincias (codpro, nombre) values ('51','CEUTA');
insert into provincias (codpro, nombre) values ('52','MELILLA');
insert into provincias (codpro, nombre) values ('99','ANDORRA');
insert into provincias (codpro, nombre) values ('00','Extranjero');
commit;