REM EJER1
CREATE TABLE USUARIOS
(
    NUMTELF NUMBER(9),
    NIA NUMBER(6) NOT NULL,
    NOMBRE VARCHAR(15),
    FOTO BLOB,
    ESTADO VARCHAR(30) DEFAULT ('Disponible'),
    CONSTRAINT PK_USUARIOS PRIMARY KEY (NUMTELF),
    CONSTRAINT CHECK_NO_MENOS_9_NUMEROS_TELEFONO CHECK (NUMTELF > 99999999),
    CONSTRAINT USUARIO_UNICO UNIQUE(NOMBRE),
    CONSTRAINT NIA_UNICO UNIQUE(NIA)
);
CREATE TABLE CHAT
(
    CODIGO NUMBER(12),
    NOMBRE VARCHAR(30) NOT NULL,
    FOTO BLOB,
    CONSTRAINT PK_CHAT PRIMARY KEY (CODIGO)
);
CREATE TABLE PARTICIPA
(
    USUARIO NUMBER(9),
    CHAT NUMBER(12),
    CONSTRAINT PK_PARTICIPA PRIMARY KEY (USUARIO,CHAT),
    CONSTRAINT FK_PARTICIPA_CHAT FOREIGN KEY(CHAT) REFERENCES CHAT (CODIGO),
    CONSTRAINT FK_PARTICIPA_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIOS (NUMTELF)
);
CREATE TABLE MENSAJE
(
    USUARIO NUMBER(9),
    CHAT NUMBER(12),
    MENSAJE CLOB NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MENSAJE PRIMARY KEY (USUARIO,CHAT,FECHA),
    CONSTRAINT FK_MENSAJE_CHAT FOREIGN KEY (CHAT) REFERENCES CHAT (CODIGO),
    CONSTRAINT FK_MENSAJE_USUARIO FOREIGN KEY (USUARIO) REFERENCES USUARIOS (NUMTELF)
);

REM EJER2
REM A
INSERT INTO USUARIOS (NUMTELF) VALUES (55512312);
REM B
DELETE FROM USUARIOS WHERE NUMTELF = 55512312;
REM D
INSERT INTO USUARIOS (NUMTELF) VALUES (555123123);
REM EJER3
REM B
INSERT INTO USUARIOS (NUMTELF,NIA,ESTADO) VALUES (555123456,1,'En clase');
INSERT INTO USUARIOS (NUMTELF,NIA,ESTADO) VALUES (555111222,2,'Ocupado');
REM EJER4
REM B
INSERT INTO USUARIOS (NUMTELF,NIA) VALUES (555123123,1);
INSERT INTO USUARIOS (NUMTELF,NIA,ESTADO,NOMBRE) VALUES (555111222,2,'Ocupado','Irati');
INSERT INTO USUARIOS (NUMTELF,NIA,ESTADO,NOMBRE) VALUES (555666777,3,'En clase','Martin');
REM C
INSERT INTO CHAT (NOMBRE,CODIGO) VALUES ('Prueba chat directo',1);
INSERT INTO CHAT (NOMBRE,CODIGO) VALUES ('Prueba chat de grupo',2);
REM D
INSERT INTO PARTICIPA (USUARIO,CHAT) VALUES (555123123,2);
INSERT INTO PARTICIPA (USUARIO,CHAT) VALUES (555111222,1);
INSERT INTO PARTICIPA (USUARIO,CHAT) VALUES (555111222,2);
INSERT INTO PARTICIPA (USUARIO,CHAT) VALUES (555666777,1);
INSERT INTO PARTICIPA (USUARIO,CHAT) VALUES (555666777,2);
REM E
INSERT INTO MENSAJE (USUARIO,CHAT,MENSAJE) VALUES (555111222,1,'Hola chat directo soy Irati');
INSERT INTO MENSAJE (USUARIO,CHAT,MENSAJE) VALUES (555666777,1,'Hola chat directo soy Martin');
INSERT INTO MENSAJE (USUARIO,CHAT,MENSAJE) VALUES (555123123,2,'Hola chat grupo no tengo nombre');

