REM EJER 7
SELECT RE.NAME NAME, M.TITLE TITLE
FROM MOVIE M, REVIEWER RE,RATING RA1, RATING RA2
WHERE RA1.RID = RA2.RID AND RA1.MID = RA2.MID AND RA1.RATINGDATE > RA2.RATINGDATE AND RA1.STARS > RA2.STARS AND RE.RID = RA1.RID AND M.MID = RA1.MID

REM EJER 12
SELECT DISTINCT RE1.NAME NAME,RE2.NAME NAME
FROM REVIEWER RE1, REVIEWER RE2, RATING RA1, RATING RA2
WHERE RE1.RID = RA1.RID AND RE2.RID = RA2.RID AND RE1.RID != RE2.RID AND RA1.MID = RA2.MID AND RE1.NAME < RE2.NAME