REM EJER19
SELECT A.CURSO, MAX(A.ALUMNOS) MAYOR_NUM_ALUMNOS, MIN(A.ALUMNOS) MENOR_NUM_ALUMNOS, AVG(A.ALUMNOS) MEDIA_NUM_ALUMNOS
FROM ASIGNATURAS A, DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS
GROUP BY A.CURSO

REM EJER20
SELECT L.NOMBRE,L.EDIFICIO,MAX(A.CURSO) CURSO_MAS_ALTO
FROM ASIGNATURAS A, LOCALES L,DOCENCIA D
WHERE D.LOCAL=L.CODIGO AND D.SIGLAS=A.SIGLAS
GROUP BY L.NOMBRE,L.EDIFICIO
ORDER BY L.NOMBRE

REM EJER21
SELECT A.NOMBRE,D.DIA, COUNT(DISTINCT P.CODIGO) NO_TIEMPO_COMPLETO
FROM DOCENCIA D, ASIGNATURAS A,PROFESORES P
WHERE A.SIGLAS=D.SIGLAS AND P.DEDICACION != 'TC' AND P.CODIGO=D.PROFESOR
GROUP BY A.NOMBRE,D.DIA
HAVING COUNT(DISTINCT P.CODIGO)>1

REM EJER22
SELECT A.NOMBRE||' ('||A.SIGLAS||')' ASIGNATURA, AVG(A.ALUMNOS)/COUNT(D.ID) ALUMNOS_POR_CLASE
FROM ASIGNATURAS A, DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS
GROUP BY A.NOMBRE,A.SIGLAS

REM EJER23
SELECT G.NOMBRE GRUPO, COUNT(DISTINCT D.PROFESOR) DISTINTOS_PROFESORES
FROM GRUPOS G, DOCENCIA D
WHERE D.CURSO=G.CURSO AND D.CLASE=G.CLASE AND D.GRUPO=G.CODIGO
GROUP BY G.NOMBRE

REM EJER24
SELECT G.NOMBRE GRUPO
FROM GRUPOS G, DOCENCIA D
WHERE D.CURSO=G.CURSO AND D.CLASE=G.CLASE AND D.GRUPO=G.CODIGO
GROUP BY G.NOMBRE
REM REVISAR ESTE

REM EJER25
SELECT P.APELLIDO1||' '||P.APELLIDO2||', '||P.NOMBRE_PILA, COUNT(DISTINCT A.SIGLAS)
FROM ASIGNATURAS A, PROFESORES P,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND D.PROFESOR=P.CODIGO
GROUP BY P.APELLIDO1,P.APELLIDO2,P.NOMBRE_PILA
ORDER BY P.APELLIDO1

REM EJER 26
SELECT P.APELLIDO1||' '||P.APELLIDO2||', '||P.NOMBRE_PILA
FROM ASIGNATURAS A, PROFESORES P,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND D.PROFESOR=P.CODIGO
GROUP BY P.APELLIDO1,P.APELLIDO2,P.NOMBRE_PILA
HAVING COUNT(DISTINCT A.SIGLAS)>1
ORDER BY P.APELLIDO1

REM EJER 27
SELECT L.NOMBRE, L.EDIFICIO, L.CAPACIDAD-AVG(A.ALUMNOS),A.NOMBRE,COUNT(DISTINCT L.CODIGO)
FROM LOCALES L, ASIGNATURAS A,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND D.LOCAL=L.CODIGO
GROUP BY L.NOMBRE,L.EDIFICIO,A.NOMBRE,L.CAPACIDAD
REM REVISAR ESTE