REM EJER1
INSERT INTO CLASE (LETRA,DIAS) VALUES ('A',7);
INSERT INTO CLASE (LETRA,DIAS) VALUES ('B',30);
INSERT INTO CLASE (LETRA,DIAS) VALUES ('C',90);
INSERT INTO CLASE (LETRA,DIAS) VALUES ('D',180);
INSERT INTO CLASE (LETRA,DIAS) VALUES ('E',365);
INSERT INTO USUARIO (NOMBRE,APELLIDO,SEXO,EDAD,NUMERO_USUARIO) VALUES ('Antonio','Gómez','Hombre',20,1);
INSERT INTO LIBRO (ISBN) VALUES ('4A');
INSERT INTO PRESTAMOS (FECHA_PETICION,NUMERO_USUARIO,ISBN) VALUES ('7/12/20',1,'4A');

REM EJER2
UPDATE PRESTAMOS SET FECHA_DEVOLUCION = '7/5/21' WHERE ISBN = '4A' AND NUMERO_USUARIO = 1 AND FECHA_PETICION = '7/12/20';

REM EJER3
INSERT INTO PRESTAMOS (FECHA_PETICION,FECHA_DEVOLUCION,NUMERO_USUARIO,ISBN) VALUES ('1/10/2016','2/10/2016',1,'4A');
DELETE FROM PRESTAMOS WHERE FECHA_DEVOLUCION <  '1/11/2016';

REM EJER4
REM QUE NOS SALE ERROR PORQUE LA EDAD MINIMA DE USUARIO ES 15

REM EJER5
INSERT INTO CLASE (LETRA, DIAS) VALUES ('F', 15);
INSERT INTO LIBRO (EDITORIAL,ISBN,LETRA) VALUES ('Anaya','1FBD','F');
INSERT INTO LIBRO (EDITORIAL,ISBN,LETRA) VALUES ('Anaya','2FBD','F');
INSERT INTO LIBRO (EDITORIAL,ISBN,LETRA) VALUES ('Anaya','3FBD','F');

REM EJER6
UPDATE CLASE SET DIAS = DIAS+30 WHERE LETRA = 'B';


REM EJER7
DELETE FROM PRESTAMOS WHERE NUMERO_USUARIO = 1;
DELETE FROM USUARIO WHERE NUMERO_USUARIO = 1;

REM EJER8
INSERT INTO USUARIO (NOMBRE,APELLIDO,SEXO,EDAD,NUMERO_USUARIO) VALUES ('Antonio','Gómez','Hombre',20,1);
INSERT INTO USUARIO (NOMBRE,APELLIDO,SEXO,NUMERO_USUARIO) VALUES ('Rosa','Pérez','Mujer',2);
INSERT INTO USUARIO (NOMBRE,APELLIDO,SEXO,NUMERO_USUARIO) VALUES ('Lucas','Pérez','Hombre',3);
INSERT INTO PRESTAMOS VALUES ('27/10/20','11/11/20',2,'1FBD');
INSERT INTO PRESTAMOS VALUES ('27/10/20','11/11/20',3,'2FBD');
INSERT INTO PRESTAMOS VALUES ('27/10/20','11/11/20',1,'3FBD');

REM EJER9
UPDATE PRESTAMOS SET FECHA_DEVOLUCION = '3/11/2020' WHERE NUMERO_USUARIO IN (1,2,3) AND FECHA_PETICION = '27/10/20' AND ISBN IN ('1FBD','2FBD','3FBD');

REM EJER10
DELETE FROM PRESTAMOS WHERE FECHA_DEVOLUCION IS NOT NULL;