CREATE TABLE LIBRO(
    TITULO VARCHAR2(100),
    EDITORIAL VARCHAR2(100),
    AUTOR VARCHAR2(100),
    ISBN VARCHAR2(100),
    LETRA VARCHAR2(1),
    CONSTRAINT PK_LIBRO PRIMARY KEY(ISBN),
    CONSTRAINT FK_LIBRO2 FOREIGN KEY(LETRA) REFERENCES CLASE (LETRA),
    CONSTRAINT TITULO_UNICO UNIQUE (TITULO)
);
CREATE TABLE USUARIO(
    NUMERO_USUARIO NUMBER(3),
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100) NOT NULL,
    SEXO VARCHAR2(100),
    EDAD NUMBER(3),
    CONSTRAINT PK_USUARIO PRIMARY KEY(NUMERO_USUARIO),
    CONSTRAINT CHECK_USUARIO CHECK(EDAD >= 15)
);
CREATE TABLE CLASE(
    LETRA VARCHAR2(1),
    DIAS NUMBER(3),
    CONSTRAINT PK_CLASE PRIMARY KEY(LETRA)
);
CREATE TABLE PRESTAMOS(
    FECHA_PETICION DATE,
    FECHA_DEVOLUCION DATE,
    NUMERO_USUARIO NUMBER(3),
    ISBN VARCHAR2(100),
    CONSTRAINT PK_PRESTAMOS PRIMARY KEY(NUMERO_USUARIO,ISBN,FECHA_PETICION),
    CONSTRAINT FK_PRESTAMOS FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
    CONSTRAINT FK_PRESTAMOS2 FOREIGN KEY (NUMERO_USUARIO) REFERENCES USUARIO(NUMERO_USUARIO),
    CONSTRAINT CHECK_FECHA_PRESTAMOS CHECK (FECHA_PETICION < FECHA_DEVOLUCION)
);