REM EJER1
SELECT DEPARTAMENTOS.CODIGO, DEPARTAMENTOS.NOMBRE, AREAS.CODIGO, AREAS.NOMBRE
FROM DEPARTAMENTOS, AREAS
WHERE DEPARTAMENTOS.CODIGO=AREAS.DEPARTAMENTO
ORDER BY DEPARTAMENTOS.CODIGO,AREAS.CODIGO DESC


REM EJER2
SELECT DOCENCIA.*
FROM DOCENCIA, LOCALES
WHERE DOCENCIA.CURSO=1 AND DOCENCIA.LOCAL=LOCALES.CODIGO AND LOCALES.CAPACIDAD>100


REM EJER3
SELECT DISTINCT PROFESORES.CODIGO, PROFESORES.APELLIDO1, PROFESORES.APELLIDO2, PROFESORES.NOMBRE_PILA
FROM PROFESORES, ASIGNATURAS,DOCENCIA
WHERE (ASIGNATURAS.NOMBRE LIKE 'Bases de Datos') AND (ASIGNATURAS.SIGLAS=DOCENCIA.SIGLAS) AND (DOCENCIA.PROFESOR=PROFESORES.CODIGO)
ORDER BY PROFESORES.APELLIDO1,PROFESORES.APELLIDO2,PROFESORES.NOMBRE_PILA DESC

REM EJER4
SELECT DISTINCT GRUPOS.*,DOCENCIA.*
FROM GRUPOS,DOCENCIA,ASIGNATURAS
WHERE (GRUPOS.CODIGO=DOCENCIA.GRUPO) AND (ASIGNATURAS.NOMBRE LIKE 'Bases de Datos') AND (ASIGNATURAS.SIGLAS=DOCENCIA.SIGLAS)


REM EJER5
SELECT DISTINCT PROFESORES.CODIGO, PROFESORES.NOMBRE_PILA, ASIGNATURAS.NOMBRE, ASIGNATURAS.ALUMNOS
FROM PROFESORES,ASIGNATURAS,DOCENCIA
WHERE (ASIGNATURAS.SIGLAS=DOCENCIA.SIGLAS) AND (DOCENCIA.PROFESOR=PROFESORES.CODIGO)
ORDER BY ASIGNATURAS.ALUMNOS DESC, PROFESORES.CODIGO ASC


REM EJER6
SELECT DISTINCT DEPARTAMENTOS.NOMBRE||' ('||DEPARTAMENTOS.CODIGO||')' "DEPARTAMENTOS",GRUPOS.NOMBRE
FROM GRUPOS,DEPARTAMENTOS,PROFESORES,DOCENCIA,AREAS
WHERE DEPARTAMENTOS.CODIGO=AREAS.DEPARTAMENTO AND AREAS.CODIGO=PROFESORES.AREA AND GRUPOS.CODIGO=DOCENCIA.GRUPO AND PROFESORES.CODIGO=DOCENCIA.PROFESOR AND DOCENCIA.CLASE=GRUPOS.CLASE AND DOCENCIA.CURSO=GRUPOS.CURSO
ORDER BY "DEPARTAMENTOS" DESC
REM EL ORDER BY SE EJECUTA LO ULTIMO, LUEGO LOS CAMPOS PUEDEN VARIAR: MEJOR RELACIONAR POR ALIAS


REM EJER7
SELECT DISTINCT ASIGNATURAS.NOMBRE,ASIGNATURAS.SIGLAS,DOCENCIA.DIA,DOCENCIA.HORA,LOCALES.CODIGO,LOCALES.NOMBRE
FROM LOCALES,ASIGNATURAS,DOCENCIA
WHERE (ASIGNATURAS.ANUALIDAD IS NULL OR ASIGNATURAS.SIGLAS IN ('ACo','BDa','DES','Eco','Fis-G')) AND DOCENCIA.SIGLAS=ASIGNATURAS.SIGLAS AND DOCENCIA.LOCAL=LOCALES.CODIGO
ORDER BY ASIGNATURAS.SIGLAS,DOCENCIA.DIA ASC, DOCENCIA.HORA DESC


REM EJER8
SELECT DISTINCT ASIGNATURAS.NOMBRE "ASIGNATURAS", GRUPOS.NOMBRE "GRUPOS",ASIGNATURAS.ALUMNOS/ASIGNATURAS.GRUPOS_PRACTICA "AlumnosxGrupo"
FROM ASIGNATURAS,GRUPOS,DOCENCIA
WHERE DOCENCIA.CLASE LIKE 'P' AND DOCENCIA.HORA NOT BETWEEN 11.3 AND 19.3 AND GRUPOS.CODIGO=DOCENCIA.GRUPO AND GRUPOS.CURSO=DOCENCIA.CURSO AND GRUPOS.CLASE=DOCENCIA.CLASE AND DOCENCIA.SIGLAS=ASIGNATURAS.SIGLAS
ORDER BY "AlumnosxGrupo" DESC, "ASIGNATURAS","GRUPOS" ASC