REM EJER2
SELECT *
FROM INGRESOS, EMPLEADO, DEPHOSPITAL, PACIENTE, HOSPITAL, TRABAJA

REM EJER3
SELECT CODHOSP, NOMHOSP, NUMEMP
FROM HOSPITAL
WHERE CIUDAD='Pamplona'

REM EJER4
SELECT COUNT(CODHOSP) TOTAL
FROM HOSPITAL
GROUP BY CODHOSP

REM EJER5
SELECT COUNT(*) TOTAL
FROM HOSPITAL
WHERE NUMEMP>4

REM EJER6
SELECT *
FROM EMPLEADO E
ORDER BY CUALIFICACION

REM EJER7
SELECT COUNT(*) TOT_AUXILIARES
FROM EMPLEADO
WHERE CUALIFICACION='AUXILIAR'

REM EJER8
SELECT COUNT(*) TOT_AUXILIARES_DEP3
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.CUALIFICACION='AUXILIAR' AND D.CODDEPT='D3'AND E.DEPAR=D.CODDEPT

REM EJER9
SELECT H.NOMHOSP,COUNT(*) TOT_AUXILIARES_DEP3
FROM EMPLEADO E, DEPHOSPITAL D,TRABAJA T, HOSPITAL H
WHERE E.CUALIFICACION='AUXILIAR' AND D.CODDEPT='D3'AND E.DEPAR=D.CODDEPT AND T.CODHOSP=H.CODHOSP AND E.DNI=T.DNI
GROUP BY H.NOMHOSP

REM EJER 10
SELECT E.DNI,E.AP1,D.CODDEPT
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.CUALIFICACION='DOCTOR' AND D.NOMDEPT='PEDIATRIA' AND E.DEPAR=D.CODDEPT

REM EJER11
SELECT E.DNI,E.AP1,E.SUELDO,T.CODHOSP
FROM EMPLEADO E, TRABAJA T
WHERE E.DNI=T.DNI

REM EJER12
SELECT E.DNI, E.AP1, E.SUELDO, COUNT(*) NUM_HOSP
FROM EMPLEADO E, TRABAJA T
WHERE E.DNI=T.DNI
GROUP BY E.SUELDO, E.AP1,E.DNI
ORDER BY NUM_HOSP DESC

REM EJER13
SELECT COUNT(*) INGRESOS
FROM INGRESOS
WHERE FECHA > '01/01/2019'

REM EJER14
SELECT D.NOMDEPT, COUNT(*) INGRESOS
FROM INGRESOS I,EMPLEADO E, DEPHOSPITAL D
WHERE I.DNI=E.DNI AND E.DEPAR=D.CODDEPT AND D.NOMDEPT='PEDIATRIA' AND I.FECHA > '01/01/2019'
GROUP BY D.NOMDEPT